spring:
  application:
    name: file-loader-service
  datasource:
    url: jdbc:postgresql://127.0.0.1:5434/ussd
    username: postgres
    password: fileloader
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        globally_quoted_identifiers: true
        jdbc:
          batch_size: 500
        order_inserts: true
    open-in-view: false

file-loader:
  input-directory: ./ussd-inputs
  archive-directory: ./ussd-inputs/archive
  batch-size: 500
